### ISSUE TITLE
Prepare Events API for further development

### ISSUE THREAD

**Issue by dantetemplar** [one-zero-eight/InNoHassle-Events#15]
## Refactoring
- [x] Break up chunks of code that are too coherent;
- [x] Divide the God-objects into their respective modules (UserRepository);
- [x] Avoid repeating minor code snippets (pull them out into the shared modules);
- [x] Refactor FastAPI dependencies.

## Improve documentation
- [x] Enhance README.md file
- [ ] Update docstrings for routes; —  Moved to the next sprint. #31 
- [ ] Update docstrings for pydantic schemas; — Moved to the next sprint. #31 
- [ ] Update docstrings for repositories. — Moved to the next sprint. #31 

## Describe new routers and schemas:
- [x] User (auth, favorites, groups) #22;
- [x] Event Group (CRUD, .ical file, link, subscription, search);
- [ ] Tag (CRUD, search) — Moved to the next sprint. #30
