### ISSUE TITLE
Deliver updates of the system to end-user

### ISSUE THREAD

**Issue by dantetemplar** [one-zero-eight/InNoHassle-Events#27]
- [x] Deploy the database to the server
- [x] Deploy the API to the server
- [x] Connect API with database
- [x] Connect website with API
