### ISSUE TITLE
[Feature] Introduce bootcamp workshop check-in

### ISSUE THREAD

**Issue by dantetemplar** [one-zero-eight/InNoHassle-Events#39]
# User Story

**As a** user

**I want to** want to register for the **bootcamp** workshop at the service

**So that** there is a place for me at the event itself, and also so that the host knows that I want to attend his workshop.

# Details

### API side
- [ ] Storage model for workshop and check-ins (workshop: name, alias, capacity, comments, date, timeslots; check-in: user_id, workshop_id, date timestamp)
- [ ] API routes to check-in and check-out
- [ ] API route to view workshop check-ins
- [ ] API route to view user's check-ins
- [ ] Optional: add constraints based on time (registration from evening to 12 noon before workshop)

### Frontend side
- [ ] View workshops separated by days
- [ ] Select workshop and view workshop's fields
- [ ] Check-in \ Check-out to workshops
- [ ] View list of attendees (with sorting by timestamp and with separating line for capacity constraint)
- [ ] View list of user's check-ins

**Comment by ArtemSBulgakov** [comment]
Should be done via #46
