### ISSUE TITLE
Get suggestions based on Innopolis group lists

### ISSUE THREAD

**Issue by dantetemplar** [one-zero-eight/InNoHassle-Events#8]
- [x] Implement auth through Innopolis SSO. #18
- [x] Parse Innopolis group lists into convenient format.
- [x] Develop an interface for authorization
- [x] Develop an interface to view suggestions on the website.

# User Story

**As a** student

**I want to** log into the service using Innopolis SSO and view my groups

**So that** I can easily add my groups without searching
